version: "3"
services:

  redis:
    image: "redis:6.2.1-alpine"
    container_name: "redis"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - sdnet

networks:
  sdnet:
    driver: "bridge"

volumes:
  redis-data:
    driver: "local"
